apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: microservice-app-example
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
        any-name: frontend
  template:
    metadata:
      labels:
        app: microservice-app-example
        any-name: frontend
    spec:
      containers:
      - env:
        - name: AUTH_API_ADDRESS
          value: http://auth-api:8081
        - name: PORT
          value: "8080"
        - name: TODOS_API_ADDRESS
          value: http://todos-api:8082
        - name: ZIPKIN_URL
          value: http://zipkin:9411/api/v2/spans
        image: frontend
        name: frontend
        ports:
        - containerPort: 8080
        imagePullPolicy: Never
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: microservice-app-example
  name: frontend
spec:
  ports:
  - port: 8080
  selector:
    service: frontend
#  type: LoadBalancer    
