apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: microservice-app-example
  name: redis-queue
spec:
  replicas: 1
  selector:
    matchLabels:
        any-name: redis-queue
  template:
    metadata:
      labels:
        app: microservice-app-example
        any-name: redis-queue
    spec:
      containers:
      - env:
        image: redis
        name: redis-queue
        ports:
        - containerPort: 6379
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: microservice-app-example
  name: redis-queue
spec:
  ports:
  - port: 6379
  selector:
    any-name: redis-queue  