apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: microservice-app-example
  name: users-api
spec:
  replicas: 1
  selector:
    matchLabels:
        any-name: users-api
  template:
    metadata:
      labels:
        app: microservice-app-example
        any-name: users-api
    spec:
      containers:
      - env:
        - name: JWT_SECRET
          value: myfancysecret
        - name: SERVER_PORT
          value: "8083"
        - name: SPRING_ZIPKIN_BASE_URL
          value: http://zipkin:9411
        image: tzvifriedman/users-api
        name: users-api
        ports:
        - containerPort: 8083
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: microservice-app-example
  name: users-api
spec:
  ports:
  - port: 8083
  selector:
    any-name: users-api    