name: learn-github-actions
run-name: ${{ github.actor }} is trying out this newfangled actions shenanigans
on: [push]
jobs:
  docker-compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yaml"
          down-flags: "--volumes"
          services: |
            frontend
            auth-api
            users-api
            log-message-processor
            todos-api
            zipkin
            redis-queue
  yaml-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/k8s-lint@v1
        with:
          manifests: |
            ./k8s/auth-api/deployment.yaml
            ./k8s/frontend/deployment.yaml
            ./k8s/log-message-processor/deployment.yaml
            ./k8s/redis-queue/deployment.yaml
            ./k8s/todos-api/deployment.yaml
            ./k8s/users-api/deployment.yaml
            ./k8s/zipkin/deployment.yaml
          kubeconformOpts: -summary
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERLOGIN }}
          password: ${{ secrets.DOCKERPASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: tzvifriedman/frontend

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}