name: learn-github-actions
run-name: ${{ github.actor }} is trying out this newfangled actions shenanigans
on: [push]
jobs:
  docker-compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yaml"
          down-flags: "--volumes"
          services: |
            frontend
            auth-api
            users-api
            log-message-processor
            todos-api
            zipkin
            redis-queue
  yaml-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/k8s-lint@v1
        with:
          manifests: |
            ./k8s/auth-api/deployment.yaml
            ./k8s/frontend/deployment.yaml
            ./k8s/log-message-processor/deployment.yaml
            ./k8s/redis-queue/deployment.yaml
            ./k8s/todos-api/deployment.yaml
            ./k8s/users-api/deployment.yaml
            ./k8s/zipkin/deployment.yaml
          kubeconformOpts: -summary
