name: learn-github-actions
run-name: ${{ github.actor }} is trying out this newfangled actions shenanigans
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  docker-compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: isbang/compose-ation@v1.5.1
        with:
          compose-file: "./docker-compose.yaml"
          down-flags: "--volumes"
          services: |
            frontend
            auth-api
            users-api
            log-message-processor
            todos-api
            zipkin
            redis-queue




